Add step to run unit tests and publish report

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -22,5 +22,16 @@ jobs:
 
     - name: Grant execute permission for gradlew
       run: chmod +x gradlew
+
     - name: Build with Gradle
       run: ./gradlew build
+
+    - name: Run unit tests
+      run: ./gradlew test
+
+    - name: Test Report
+      uses: dorny/test-reporter@v1      
+      if: success() || failure()        # run this step even if previous step failed
+      with:
+        name: JUnit Tests
+        path: app/build/test-results/**/TEST-*.xml
